export type NutriMinimalProductizationClass =
  | "low_risk_structural"
  | "high_risk_safety"
  | "crosswalk_rescue";

export type NutriMinimalSafetyBoundaryTier = "standard" | "high";

export type NutriMinimalFullFamilyDefinition = {
  sourceIngredientId: string;
  canonicalFamily: string;
  displayName: string;
  category: string;
  productizationClass: NutriMinimalProductizationClass;
  safetyBoundaryTier: NutriMinimalSafetyBoundaryTier;
  categoryHint: string;
  patternKeywords: string[];
  pattern: RegExp;
  preferredGoals: string[];
  hardBoundary: string;
};

export const NUTRI_MINIMAL_FULL_FAMILY_DEFINITIONS = [
  {
    sourceIngredientId: "amylase",
    canonicalFamily: "amylase",
    displayName: "Amylase",
    category: "enzyme",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "enzyme",
    patternKeywords: ["Amylase","amylase"],
    pattern: /\b(?:Amylase|amylase)\b/i,
    preferredGoals: ["digestive","general_wellness"],
    hardBoundary: "Do not turn Amylase context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "artichoke_extract",
    canonicalFamily: "artichoke_extract",
    displayName: "Artichoke extract",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Artichoke extract","artichoke extract","artichoke leaf","cynara"],
    pattern: /\b(?:Artichoke[\s_-]+extract|artichoke[\s_-]+extract|artichoke[\s_-]+leaf|cynara)\b/i,
    preferredGoals: ["liver","digestive"],
    hardBoundary: "Hard boundary: do not present Artichoke Extract as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "bacopa_monnieri",
    canonicalFamily: "bacopa_monnieri",
    displayName: "Bacopa monnieri",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Bacopa monnieri","bacopa monnieri","bacopa","bacosides"],
    pattern: /\b(?:Bacopa[\s_-]+monnieri|bacopa[\s_-]+monnieri|bacopa|bacosides)\b/i,
    preferredGoals: ["cognitive","general_wellness"],
    hardBoundary: "Hard boundary: do not present Bacopa Monnieri as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "bee_propolis",
    canonicalFamily: "bee_propolis",
    displayName: "Bee Propolis",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Bee Propolis","bee propolis"],
    pattern: /\b(?:Bee[\s_-]+Propolis|bee[\s_-]+propolis)\b/i,
    preferredGoals: ["immune","general_wellness"],
    hardBoundary: "Hard boundary: do not present Bee Propolis as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "beta_carotene",
    canonicalFamily: "beta_carotene",
    displayName: "Beta-Carotene",
    category: "lipid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "lipid ingredient",
    patternKeywords: ["Beta-Carotene","beta carotene"],
    pattern: /\b(?:Beta[\s_-]+Carotene|beta[\s_-]+carotene)\b/i,
    preferredGoals: ["heart_lipids","general_wellness"],
    hardBoundary: "Do not turn Beta Carotene context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "bilberry",
    canonicalFamily: "bilberry",
    displayName: "Bilberry",
    category: "botanical",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "botanical extract",
    patternKeywords: ["Bilberry","bilberry"],
    pattern: /\b(?:Bilberry|bilberry)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Do not turn Bilberry context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "bitter_melon",
    canonicalFamily: "bitter_melon",
    displayName: "Bitter Melon",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Bitter Melon","bitter melon"],
    pattern: /\b(?:Bitter[\s_-]+Melon|bitter[\s_-]+melon)\b/i,
    preferredGoals: ["metabolic","general_wellness"],
    hardBoundary: "Hard boundary: do not present Bitter Melon as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "black_cohosh",
    canonicalFamily: "black_cohosh",
    displayName: "Black Cohosh",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Black Cohosh","black cohosh","actaea racemosa","cimicifuga"],
    pattern: /\b(?:Black[\s_-]+Cohosh|black[\s_-]+cohosh|actaea[\s_-]+racemosa|cimicifuga)\b/i,
    preferredGoals: ["womens_health","general_wellness"],
    hardBoundary: "Hard boundary: do not present Black Cohosh as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "borage_oil",
    canonicalFamily: "borage_oil",
    displayName: "Borage Oil",
    category: "lipid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "oil ingredient",
    patternKeywords: ["Borage Oil","borage oil"],
    pattern: /\b(?:Borage[\s_-]+Oil|borage[\s_-]+oil)\b/i,
    preferredGoals: ["heart_lipids","general_wellness"],
    hardBoundary: "Do not turn Borage Oil context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "boron",
    canonicalFamily: "boron",
    displayName: "Boron",
    category: "mineral",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "mineral",
    patternKeywords: ["Boron","boron"],
    pattern: /\b(?:Boron|boron)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Do not turn Boron context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "boswellia",
    canonicalFamily: "boswellia",
    displayName: "Boswellia",
    category: "botanical",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "botanical extract",
    patternKeywords: ["Boswellia","boswellia","boswellia serrata","AKBA"],
    pattern: /\b(?:Boswellia|boswellia|boswellia[\s_-]+serrata|AKBA)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Do not turn Boswellia context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "broccoli_sprout_extract",
    canonicalFamily: "broccoli_sprout_extract",
    displayName: "Broccoli Sprout Extract",
    category: "other",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "single-active ingredient",
    patternKeywords: ["Broccoli Sprout Extract","broccoli sprout extract","sulforaphane","glucoraphanin"],
    pattern: /\b(?:Broccoli[\s_-]+Sprout[\s_-]+Extract|broccoli[\s_-]+sprout[\s_-]+extract|sulforaphane|glucoraphanin)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Hard boundary: do not present Broccoli Sprout Extract as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "caffeine",
    canonicalFamily: "caffeine",
    displayName: "Caffeine",
    category: "other",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "single-active ingredient",
    patternKeywords: ["Caffeine","caffeine"],
    pattern: /\b(?:Caffeine|caffeine)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Hard boundary: do not present Caffeine as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "calcium_d_glucarate",
    canonicalFamily: "calcium_d_glucarate",
    displayName: "Calcium D-Glucarate",
    category: "other",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "single-active ingredient",
    patternKeywords: ["Calcium D-Glucarate","calcium d glucarate"],
    pattern: /\b(?:Calcium[\s_-]+D[\s_-]+Glucarate|calcium[\s_-]+d[\s_-]+glucarate)\b/i,
    preferredGoals: ["liver","digestive"],
    hardBoundary: "Hard boundary: do not present Calcium D Glucarate as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "chaga_mushroom",
    canonicalFamily: "chaga_mushroom",
    displayName: "Chaga Mushroom",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "mushroom extract",
    patternKeywords: ["Chaga Mushroom","chaga mushroom","chaga"],
    pattern: /\b(?:Chaga[\s_-]+Mushroom|chaga[\s_-]+mushroom|chaga)\b/i,
    preferredGoals: ["immune","general_wellness"],
    hardBoundary: "Hard boundary: do not present Chaga Mushroom as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "chlorella",
    canonicalFamily: "chlorella",
    displayName: "Chlorella",
    category: "other",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "single-active ingredient",
    patternKeywords: ["Chlorella","chlorella"],
    pattern: /\b(?:Chlorella|chlorella)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Do not turn Chlorella context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "chlorophyll",
    canonicalFamily: "chlorophyll",
    displayName: "Chlorophyll",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Chlorophyll","chlorophyll"],
    pattern: /\b(?:Chlorophyll|chlorophyll)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Hard boundary: do not present Chlorophyll as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "chondroitin",
    canonicalFamily: "chondroitin",
    displayName: "Chondroitin",
    category: "other",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "structural compound",
    patternKeywords: ["Chondroitin","chondroitin"],
    pattern: /\b(?:Chondroitin|chondroitin)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Do not turn Chondroitin context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "cinnamon",
    canonicalFamily: "cinnamon_extract",
    displayName: "Cinnamon",
    category: "botanical",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "botanical extract",
    patternKeywords: ["Cinnamon","cinnamon"],
    pattern: /\b(?:Cinnamon|cinnamon)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Do not turn Cinnamon Extract context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "cordyceps_mushroom",
    canonicalFamily: "cordyceps_mushroom",
    displayName: "Cordyceps Mushroom",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "mushroom extract",
    patternKeywords: ["Cordyceps Mushroom","cordyceps mushroom","cordyceps"],
    pattern: /\b(?:Cordyceps[\s_-]+Mushroom|cordyceps[\s_-]+mushroom|cordyceps)\b/i,
    preferredGoals: ["immune","general_wellness"],
    hardBoundary: "Hard boundary: do not present Cordyceps Mushroom as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "cranberry_extract",
    canonicalFamily: "cranberry_extract",
    displayName: "Cranberry extract",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Cranberry extract","cranberry extract","vaccinium macrocarpon"],
    pattern: /\b(?:Cranberry[\s_-]+extract|cranberry[\s_-]+extract|vaccinium[\s_-]+macrocarpon)\b/i,
    preferredGoals: ["urinary","general_wellness"],
    hardBoundary: "Hard boundary: do not present Cranberry Extract as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "dandelion_root",
    canonicalFamily: "dandelion_root",
    displayName: "Dandelion Root",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Dandelion Root","dandelion root"],
    pattern: /\b(?:Dandelion[\s_-]+Root|dandelion[\s_-]+root)\b/i,
    preferredGoals: ["liver","digestive"],
    hardBoundary: "Hard boundary: do not present Dandelion Root as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "devil_s_claw",
    canonicalFamily: "devil_s_claw",
    displayName: "Devil's Claw",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Devil's Claw","devil s claw","devils claw","harpagophytum"],
    pattern: /\b(?:Devil's[\s_-]+Claw|devil[\s_-]+s[\s_-]+claw|devils[\s_-]+claw|harpagophytum)\b/i,
    preferredGoals: ["joint","general_wellness"],
    hardBoundary: "Hard boundary: do not present Devil S Claw as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "dong_quai",
    canonicalFamily: "dong_quai",
    displayName: "Dong Quai",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Dong Quai","dong quai","angelica sinensis"],
    pattern: /\b(?:Dong[\s_-]+Quai|dong[\s_-]+quai|angelica[\s_-]+sinensis)\b/i,
    preferredGoals: ["womens_health","general_wellness"],
    hardBoundary: "Hard boundary: do not present Dong Quai as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "echinacea",
    canonicalFamily: "echinacea",
    displayName: "Echinacea",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Echinacea","echinacea","echinacea purpurea"],
    pattern: /\b(?:Echinacea|echinacea|echinacea[\s_-]+purpurea)\b/i,
    preferredGoals: ["immune","general_wellness"],
    hardBoundary: "Hard boundary: do not present Echinacea as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "elderberry",
    canonicalFamily: "elderberry",
    displayName: "Elderberry",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Elderberry","elderberry","sambucus"],
    pattern: /\b(?:Elderberry|elderberry|sambucus)\b/i,
    preferredGoals: ["immune","general_wellness"],
    hardBoundary: "Hard boundary: do not present Elderberry as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "eleuthero",
    canonicalFamily: "eleuthero",
    displayName: "Eleuthero",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Eleuthero","eleuthero","siberian ginseng","eleutherococcus"],
    pattern: /\b(?:Eleuthero|eleuthero|siberian[\s_-]+ginseng|eleutherococcus)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Hard boundary: do not present Eleuthero as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "evening_primrose_oil",
    canonicalFamily: "evening_primrose_oil",
    displayName: "Evening primrose oil",
    category: "lipid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "oil ingredient",
    patternKeywords: ["Evening primrose oil","evening primrose oil"],
    pattern: /\b(?:Evening[\s_-]+primrose[\s_-]+oil|evening[\s_-]+primrose[\s_-]+oil)\b/i,
    preferredGoals: ["heart_lipids","general_wellness"],
    hardBoundary: "Do not turn Evening Primrose Oil context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "fenugreek",
    canonicalFamily: "fenugreek",
    displayName: "Fenugreek",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Fenugreek","fenugreek","trigonella"],
    pattern: /\b(?:Fenugreek|fenugreek|trigonella)\b/i,
    preferredGoals: ["metabolic","general_wellness"],
    hardBoundary: "Hard boundary: do not present Fenugreek as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "forskolin",
    canonicalFamily: "forskolin",
    displayName: "Forskolin",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Forskolin","forskolin","coleus forskohlii"],
    pattern: /\b(?:Forskolin|forskolin|coleus[\s_-]+forskohlii)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Hard boundary: do not present Forskolin as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "fucoidan",
    canonicalFamily: "fucoidan",
    displayName: "Fucoidan",
    category: "botanical",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "botanical extract",
    patternKeywords: ["Fucoidan","fucoidan"],
    pattern: /\b(?:Fucoidan|fucoidan)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Do not turn Fucoidan context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "gamma_linolenic_acid",
    canonicalFamily: "gamma_linolenic_acid",
    displayName: "Gamma-Linolenic Acid",
    category: "lipid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "lipid ingredient",
    patternKeywords: ["Gamma-Linolenic Acid","gamma linolenic acid","GLA"],
    pattern: /\b(?:Gamma[\s_-]+Linolenic[\s_-]+Acid|gamma[\s_-]+linolenic[\s_-]+acid|GLA)\b/i,
    preferredGoals: ["heart_lipids","general_wellness"],
    hardBoundary: "Do not turn Gamma Linolenic Acid context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "garcinia_cambogia",
    canonicalFamily: "garcinia_cambogia",
    displayName: "Garcinia cambogia",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Garcinia cambogia","garcinia cambogia","hydroxycitric acid","HCA"],
    pattern: /\b(?:Garcinia[\s_-]+cambogia|garcinia[\s_-]+cambogia|hydroxycitric[\s_-]+acid|HCA)\b/i,
    preferredGoals: ["metabolic","general_wellness"],
    hardBoundary: "Hard boundary: do not present Garcinia Cambogia as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "ginkgo_biloba",
    canonicalFamily: "ginkgo_biloba",
    displayName: "Ginkgo biloba",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Ginkgo biloba","ginkgo biloba","ginkgo"],
    pattern: /\b(?:Ginkgo[\s_-]+biloba|ginkgo[\s_-]+biloba|ginkgo)\b/i,
    preferredGoals: ["cognitive","general_wellness"],
    hardBoundary: "Hard boundary: do not present Ginkgo Biloba as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "glucomannan",
    canonicalFamily: "glucomannan",
    displayName: "Glucomannan",
    category: "other",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "single-active ingredient",
    patternKeywords: ["Glucomannan","glucomannan"],
    pattern: /\b(?:Glucomannan|glucomannan)\b/i,
    preferredGoals: ["metabolic","general_wellness"],
    hardBoundary: "Hard boundary: do not present Glucomannan as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "glucosamine",
    canonicalFamily: "glucosamine",
    displayName: "Glucosamine",
    category: "other",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "structural compound",
    patternKeywords: ["Glucosamine","glucosamine"],
    pattern: /\b(?:Glucosamine|glucosamine)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Do not turn Glucosamine context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "grapefruit_seed_extract",
    canonicalFamily: "grapefruit_seed_extract",
    displayName: "Grapefruit Seed Extract",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Grapefruit Seed Extract","grapefruit seed extract"],
    pattern: /\b(?:Grapefruit[\s_-]+Seed[\s_-]+Extract|grapefruit[\s_-]+seed[\s_-]+extract)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Hard boundary: do not present Grapefruit Seed Extract as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "green_coffee_bean_extract",
    canonicalFamily: "green_coffee_bean_extract",
    displayName: "Green Coffee Bean Extract",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Green Coffee Bean Extract","green coffee bean extract","chlorogenic acid"],
    pattern: /\b(?:Green[\s_-]+Coffee[\s_-]+Bean[\s_-]+Extract|green[\s_-]+coffee[\s_-]+bean[\s_-]+extract|chlorogenic[\s_-]+acid)\b/i,
    preferredGoals: ["metabolic","general_wellness"],
    hardBoundary: "Hard boundary: do not present Green Coffee Bean Extract as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "gymnema",
    canonicalFamily: "gymnema",
    displayName: "Gymnema",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Gymnema","gymnema","gymnema sylvestre"],
    pattern: /\b(?:Gymnema|gymnema|gymnema[\s_-]+sylvestre)\b/i,
    preferredGoals: ["metabolic","general_wellness"],
    hardBoundary: "Hard boundary: do not present Gymnema as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "hawthorn",
    canonicalFamily: "hawthorn",
    displayName: "Hawthorn",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Hawthorn","hawthorn"],
    pattern: /\b(?:Hawthorn|hawthorn)\b/i,
    preferredGoals: ["heart_lipids","general_wellness"],
    hardBoundary: "Hard boundary: do not present Hawthorn as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "hesperidin",
    canonicalFamily: "hesperidin",
    displayName: "Hesperidin",
    category: "other",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "single-active ingredient",
    patternKeywords: ["Hesperidin","hesperidin"],
    pattern: /\b(?:Hesperidin|hesperidin)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Do not turn Hesperidin context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "holy_basil",
    canonicalFamily: "holy_basil",
    displayName: "Holy Basil",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Holy Basil","holy basil","tulsi","ocimum"],
    pattern: /\b(?:Holy[\s_-]+Basil|holy[\s_-]+basil|tulsi|ocimum)\b/i,
    preferredGoals: ["sleep_stress","mood"],
    hardBoundary: "Hard boundary: do not present Holy Basil as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "huperzine_a",
    canonicalFamily: "huperzine_a",
    displayName: "Huperzine A",
    category: "other",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "single-active ingredient",
    patternKeywords: ["Huperzine A","huperzine a","huperzia"],
    pattern: /\b(?:Huperzine[\s_-]+A|huperzine[\s_-]+a|huperzia)\b/i,
    preferredGoals: ["cognitive","general_wellness"],
    hardBoundary: "Hard boundary: do not present Huperzine A as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "hyaluronic_acid",
    canonicalFamily: "hyaluronic_acid",
    displayName: "Hyaluronic acid",
    category: "other",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "structural compound",
    patternKeywords: ["Hyaluronic acid","hyaluronic acid"],
    pattern: /\b(?:Hyaluronic[\s_-]+acid|hyaluronic[\s_-]+acid)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Do not turn Hyaluronic Acid context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "indole_3_carbinol",
    canonicalFamily: "indole_3_carbinol",
    displayName: "Indole-3-Carbinol",
    category: "other",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "single-active ingredient",
    patternKeywords: ["Indole-3-Carbinol","indole 3 carbinol","I3C"],
    pattern: /\b(?:Indole[\s_-]+3[\s_-]+Carbinol|indole[\s_-]+3[\s_-]+carbinol|I3C)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Hard boundary: do not present Indole 3 Carbinol as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "krill_oil",
    canonicalFamily: "krill_oil",
    displayName: "Krill Oil",
    category: "lipid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "oil ingredient",
    patternKeywords: ["Krill Oil","krill oil","euphausia"],
    pattern: /\b(?:Krill[\s_-]+Oil|krill[\s_-]+oil|euphausia)\b/i,
    preferredGoals: ["heart_lipids","general_wellness"],
    hardBoundary: "Do not turn Krill Oil context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "l_alanine",
    canonicalFamily: "l_alanine",
    displayName: "L-Alanine",
    category: "amino_acid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "amino acid",
    patternKeywords: ["L-Alanine","l alanine"],
    pattern: /\b(?:L[\s_-]+Alanine|l[\s_-]+alanine)\b/i,
    preferredGoals: ["energy_performance","recovery","general_wellness"],
    hardBoundary: "Do not turn L Alanine context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "l_aspartic_acid",
    canonicalFamily: "l_aspartic_acid",
    displayName: "L-Aspartic Acid",
    category: "amino_acid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "amino acid",
    patternKeywords: ["L-Aspartic Acid","l aspartic acid"],
    pattern: /\b(?:L[\s_-]+Aspartic[\s_-]+Acid|l[\s_-]+aspartic[\s_-]+acid)\b/i,
    preferredGoals: ["energy_performance","recovery","general_wellness"],
    hardBoundary: "Do not turn L Aspartic Acid context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "l_citrulline",
    canonicalFamily: "l_citrulline",
    displayName: "L-Citrulline",
    category: "amino_acid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "amino acid",
    patternKeywords: ["L-Citrulline","l citrulline"],
    pattern: /\b(?:L[\s_-]+Citrulline|l[\s_-]+citrulline)\b/i,
    preferredGoals: ["energy_performance","recovery","general_wellness"],
    hardBoundary: "Do not turn L Citrulline context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "l_glutamic_acid",
    canonicalFamily: "l_glutamic_acid",
    displayName: "L-Glutamic Acid",
    category: "amino_acid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "amino acid",
    patternKeywords: ["L-Glutamic Acid","l glutamic acid"],
    pattern: /\b(?:L[\s_-]+Glutamic[\s_-]+Acid|l[\s_-]+glutamic[\s_-]+acid)\b/i,
    preferredGoals: ["energy_performance","recovery","general_wellness"],
    hardBoundary: "Do not turn L Glutamic Acid context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "l_histidine",
    canonicalFamily: "l_histidine",
    displayName: "L-Histidine",
    category: "amino_acid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "amino acid",
    patternKeywords: ["L-Histidine","l histidine"],
    pattern: /\b(?:L[\s_-]+Histidine|l[\s_-]+histidine)\b/i,
    preferredGoals: ["energy_performance","recovery","general_wellness"],
    hardBoundary: "Do not turn L Histidine context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "l_isoleucine",
    canonicalFamily: "l_isoleucine",
    displayName: "L-Isoleucine",
    category: "amino_acid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "amino acid",
    patternKeywords: ["L-Isoleucine","l isoleucine"],
    pattern: /\b(?:L[\s_-]+Isoleucine|l[\s_-]+isoleucine)\b/i,
    preferredGoals: ["energy_performance","recovery","general_wellness"],
    hardBoundary: "Do not turn L Isoleucine context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "l_leucine",
    canonicalFamily: "l_leucine",
    displayName: "L-Leucine",
    category: "amino_acid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "amino acid",
    patternKeywords: ["L-Leucine","l leucine"],
    pattern: /\b(?:L[\s_-]+Leucine|l[\s_-]+leucine)\b/i,
    preferredGoals: ["energy_performance","recovery","general_wellness"],
    hardBoundary: "Do not turn L Leucine context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "l_phenylalanine",
    canonicalFamily: "l_phenylalanine",
    displayName: "L-Phenylalanine",
    category: "amino_acid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "amino acid",
    patternKeywords: ["L-Phenylalanine","l phenylalanine"],
    pattern: /\b(?:L[\s_-]+Phenylalanine|l[\s_-]+phenylalanine)\b/i,
    preferredGoals: ["energy_performance","recovery","general_wellness"],
    hardBoundary: "Do not turn L Phenylalanine context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "l_serine",
    canonicalFamily: "l_serine",
    displayName: "L-Serine",
    category: "amino_acid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "amino acid",
    patternKeywords: ["L-Serine","l serine"],
    pattern: /\b(?:L[\s_-]+Serine|l[\s_-]+serine)\b/i,
    preferredGoals: ["energy_performance","recovery","general_wellness"],
    hardBoundary: "Do not turn L Serine context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "l_theanine",
    canonicalFamily: "l_theanine",
    displayName: "L-Theanine",
    category: "amino_acid",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "amino acid",
    patternKeywords: ["L-Theanine","l theanine","suntheanine"],
    pattern: /\b(?:L[\s_-]+Theanine|l[\s_-]+theanine|suntheanine)\b/i,
    preferredGoals: ["sleep_stress","mood"],
    hardBoundary: "Hard boundary: do not present L Theanine as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "l_threonine",
    canonicalFamily: "l_threonine",
    displayName: "L-Threonine",
    category: "amino_acid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "amino acid",
    patternKeywords: ["L-Threonine","l threonine"],
    pattern: /\b(?:L[\s_-]+Threonine|l[\s_-]+threonine)\b/i,
    preferredGoals: ["energy_performance","recovery","general_wellness"],
    hardBoundary: "Do not turn L Threonine context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "l_tryptophan",
    canonicalFamily: "l_tryptophan",
    displayName: "L-Tryptophan",
    category: "amino_acid",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "amino acid",
    patternKeywords: ["L-Tryptophan","l tryptophan"],
    pattern: /\b(?:L[\s_-]+Tryptophan|l[\s_-]+tryptophan)\b/i,
    preferredGoals: ["sleep_stress","mood"],
    hardBoundary: "Hard boundary: do not present L Tryptophan as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "lactase",
    canonicalFamily: "lactase",
    displayName: "Lactase",
    category: "enzyme",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "enzyme",
    patternKeywords: ["Lactase","lactase"],
    pattern: /\b(?:Lactase|lactase)\b/i,
    preferredGoals: ["digestive","general_wellness"],
    hardBoundary: "Do not turn Lactase context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "lion_s_mane_mushroom",
    canonicalFamily: "lion_s_mane_mushroom",
    displayName: "Lion's Mane Mushroom",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "mushroom extract",
    patternKeywords: ["Lion's Mane Mushroom","lion s mane mushroom","lion mane","hericium"],
    pattern: /\b(?:Lion's[\s_-]+Mane[\s_-]+Mushroom|lion[\s_-]+s[\s_-]+mane[\s_-]+mushroom|lion[\s_-]+mane|hericium)\b/i,
    preferredGoals: ["immune","general_wellness"],
    hardBoundary: "Hard boundary: do not present Lion S Mane Mushroom as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "lipase",
    canonicalFamily: "lipase",
    displayName: "Lipase",
    category: "enzyme",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "enzyme",
    patternKeywords: ["Lipase","lipase"],
    pattern: /\b(?:Lipase|lipase)\b/i,
    preferredGoals: ["digestive","general_wellness"],
    hardBoundary: "Do not turn Lipase context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "lutein",
    canonicalFamily: "lutein",
    displayName: "Lutein",
    category: "other",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "carotenoid",
    patternKeywords: ["Lutein","lutein"],
    pattern: /\b(?:Lutein|lutein)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Do not turn Lutein context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "lycopene",
    canonicalFamily: "lycopene",
    displayName: "Lycopene",
    category: "other",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "carotenoid",
    patternKeywords: ["Lycopene","lycopene"],
    pattern: /\b(?:Lycopene|lycopene)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Do not turn Lycopene context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "maca",
    canonicalFamily: "maca",
    displayName: "Maca",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Maca","maca"],
    pattern: /\b(?:Maca|maca)\b/i,
    preferredGoals: ["men_health","energy_performance"],
    hardBoundary: "Hard boundary: do not present Maca as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "maitake_mushroom",
    canonicalFamily: "maitake_mushroom",
    displayName: "Maitake Mushroom",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "mushroom extract",
    patternKeywords: ["Maitake Mushroom","maitake mushroom","grifola"],
    pattern: /\b(?:Maitake[\s_-]+Mushroom|maitake[\s_-]+mushroom|grifola)\b/i,
    preferredGoals: ["immune","general_wellness"],
    hardBoundary: "Hard boundary: do not present Maitake Mushroom as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "naringin",
    canonicalFamily: "naringin",
    displayName: "Naringin",
    category: "other",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "single-active ingredient",
    patternKeywords: ["Naringin","naringin"],
    pattern: /\b(?:Naringin|naringin)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Do not turn Naringin context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "nattokinase",
    canonicalFamily: "nattokinase",
    displayName: "Nattokinase",
    category: "enzyme",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "enzyme",
    patternKeywords: ["Nattokinase","nattokinase"],
    pattern: /\b(?:Nattokinase|nattokinase)\b/i,
    preferredGoals: ["heart_lipids","general_wellness"],
    hardBoundary: "Hard boundary: do not present Nattokinase as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "pine_bark_extract",
    canonicalFamily: "pine_bark_extract",
    displayName: "Pine Bark Extract",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Pine Bark Extract","pine bark extract","pycnogenol","pinus pinaster"],
    pattern: /\b(?:Pine[\s_-]+Bark[\s_-]+Extract|pine[\s_-]+bark[\s_-]+extract|pycnogenol|pinus[\s_-]+pinaster)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Hard boundary: do not present Pine Bark Extract as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "protease",
    canonicalFamily: "protease",
    displayName: "Protease",
    category: "enzyme",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "enzyme",
    patternKeywords: ["Protease","protease"],
    pattern: /\b(?:Protease|protease)\b/i,
    preferredGoals: ["digestive","general_wellness"],
    hardBoundary: "Do not turn Protease context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "pumpkin_seed_oil",
    canonicalFamily: "pumpkin_seed_oil",
    displayName: "Pumpkin Seed Oil",
    category: "lipid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "oil ingredient",
    patternKeywords: ["Pumpkin Seed Oil","pumpkin seed oil"],
    pattern: /\b(?:Pumpkin[\s_-]+Seed[\s_-]+Oil|pumpkin[\s_-]+seed[\s_-]+oil)\b/i,
    preferredGoals: ["heart_lipids","general_wellness"],
    hardBoundary: "Do not turn Pumpkin Seed Oil context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "reishi_mushroom",
    canonicalFamily: "reishi_mushroom",
    displayName: "Reishi Mushroom",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "mushroom extract",
    patternKeywords: ["Reishi Mushroom","reishi mushroom","ganoderma"],
    pattern: /\b(?:Reishi[\s_-]+Mushroom|reishi[\s_-]+mushroom|ganoderma)\b/i,
    preferredGoals: ["immune","general_wellness"],
    hardBoundary: "Hard boundary: do not present Reishi Mushroom as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "rhodiola_rosea",
    canonicalFamily: "rhodiola_rosea",
    displayName: "Rhodiola rosea",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Rhodiola rosea","rhodiola rosea","rhodiola","rosavins","salidroside"],
    pattern: /\b(?:Rhodiola[\s_-]+rosea|rhodiola[\s_-]+rosea|rhodiola|rosavins|salidroside)\b/i,
    preferredGoals: ["sleep_stress","mood"],
    hardBoundary: "Hard boundary: do not present Rhodiola Rosea as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "saw_palmetto",
    canonicalFamily: "saw_palmetto",
    displayName: "Saw palmetto",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Saw palmetto","saw palmetto","serenoa repens"],
    pattern: /\b(?:Saw[\s_-]+palmetto|saw[\s_-]+palmetto|serenoa[\s_-]+repens)\b/i,
    preferredGoals: ["urinary","general_wellness"],
    hardBoundary: "Hard boundary: do not present Saw Palmetto as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "schisandra_chinensis",
    canonicalFamily: "schisandra_chinensis",
    displayName: "Schisandra Chinensis",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Schisandra Chinensis","schisandra chinensis","schisandra"],
    pattern: /\b(?:Schisandra[\s_-]+Chinensis|schisandra[\s_-]+chinensis|schisandra)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Hard boundary: do not present Schisandra Chinensis as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "shilajit",
    canonicalFamily: "shilajit",
    displayName: "Shilajit",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Shilajit","shilajit"],
    pattern: /\b(?:Shilajit|shilajit)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Hard boundary: do not present Shilajit as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "spermidine",
    canonicalFamily: "spermidine",
    displayName: "Spermidine",
    category: "other",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "single-active ingredient",
    patternKeywords: ["Spermidine","spermidine"],
    pattern: /\b(?:Spermidine|spermidine)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Do not turn Spermidine context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "stinging_nettle_root",
    canonicalFamily: "stinging_nettle_root",
    displayName: "Stinging Nettle Root",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Stinging Nettle Root","stinging nettle root","nettle root","urtica"],
    pattern: /\b(?:Stinging[\s_-]+Nettle[\s_-]+Root|stinging[\s_-]+nettle[\s_-]+root|nettle[\s_-]+root|urtica)\b/i,
    preferredGoals: ["urinary","general_wellness"],
    hardBoundary: "Hard boundary: do not present Stinging Nettle Root as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "tongkat_ali",
    canonicalFamily: "tongkat_ali",
    displayName: "Tongkat Ali",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Tongkat Ali","tongkat ali","eurycoma","longjack"],
    pattern: /\b(?:Tongkat[\s_-]+Ali|tongkat[\s_-]+ali|eurycoma|longjack)\b/i,
    preferredGoals: ["men_health","energy_performance"],
    hardBoundary: "Hard boundary: do not present Tongkat Ali as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "urolithin_a",
    canonicalFamily: "urolithin_a",
    displayName: "Urolithin A",
    category: "other",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "single-active ingredient",
    patternKeywords: ["Urolithin A","urolithin a"],
    pattern: /\b(?:Urolithin[\s_-]+A|urolithin[\s_-]+a)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Do not turn Urolithin A context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "vitex",
    canonicalFamily: "vitex",
    displayName: "Vitex",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["Vitex","vitex","chasteberry","chaste tree"],
    pattern: /\b(?:Vitex|vitex|chasteberry|chaste[\s_-]+tree)\b/i,
    preferredGoals: ["womens_health","general_wellness"],
    hardBoundary: "Hard boundary: do not present Vitex as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "white_willow_bark",
    canonicalFamily: "white_willow_bark",
    displayName: "White Willow Bark",
    category: "botanical",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "botanical extract",
    patternKeywords: ["White Willow Bark","white willow bark","salix alba"],
    pattern: /\b(?:White[\s_-]+Willow[\s_-]+Bark|white[\s_-]+willow[\s_-]+bark|salix[\s_-]+alba)\b/i,
    preferredGoals: ["joint","general_wellness"],
    hardBoundary: "Hard boundary: do not present White Willow Bark as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "d_mannose",
    canonicalFamily: "d_mannose",
    displayName: "D-Mannose",
    category: "other",
    productizationClass: "high_risk_safety",
    safetyBoundaryTier: "high",
    categoryHint: "single-active ingredient",
    patternKeywords: ["D-Mannose","d mannose"],
    pattern: /\b(?:D[\s_-]+Mannose|d[\s_-]+mannose)\b/i,
    preferredGoals: ["urinary","general_wellness"],
    hardBoundary: "Hard boundary: do not present D-mannose as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "l_glutamine",
    canonicalFamily: "l_glutamine",
    displayName: "L-Glutamine",
    category: "amino_acid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "amino acid",
    patternKeywords: ["L-Glutamine","l glutamine"],
    pattern: /\b(?:L[\s_-]+Glutamine|l[\s_-]+glutamine)\b/i,
    preferredGoals: ["energy_performance","recovery","general_wellness"],
    hardBoundary: "Do not turn L Glutamine context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "l_lysine",
    canonicalFamily: "l_lysine",
    displayName: "L-Lysine",
    category: "amino_acid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "amino acid",
    patternKeywords: ["L-Lysine","l lysine"],
    pattern: /\b(?:L[\s_-]+Lysine|l[\s_-]+lysine)\b/i,
    preferredGoals: ["energy_performance","recovery","general_wellness"],
    hardBoundary: "Do not turn L Lysine context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "l_tyrosine",
    canonicalFamily: "l_tyrosine",
    displayName: "L-Tyrosine",
    category: "amino_acid",
    productizationClass: "low_risk_structural",
    safetyBoundaryTier: "standard",
    categoryHint: "amino acid",
    patternKeywords: ["L-Tyrosine","l tyrosine"],
    pattern: /\b(?:L[\s_-]+Tyrosine|l[\s_-]+tyrosine)\b/i,
    preferredGoals: ["energy_performance","recovery","general_wellness"],
    hardBoundary: "Do not turn L Tyrosine context into disease-treatment, guaranteed-outcome, universal best-form, or superiority language.",
  },
  {
    sourceIngredientId: "betaine",
    canonicalFamily: "betaine",
    displayName: "Betaine",
    category: "other",
    productizationClass: "crosswalk_rescue",
    safetyBoundaryTier: "high",
    categoryHint: "single-active ingredient",
    patternKeywords: ["Betaine","betaine"],
    pattern: /\b(?:Betaine|betaine)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Hard boundary: do not present Betaine as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "black_seed_oil",
    canonicalFamily: "black_seed_oil",
    displayName: "Black seed oil",
    category: "lipid",
    productizationClass: "crosswalk_rescue",
    safetyBoundaryTier: "high",
    categoryHint: "oil ingredient",
    patternKeywords: ["Black seed oil","black seed oil","nigella sativa","black cumin"],
    pattern: /\b(?:Black[\s_-]+seed[\s_-]+oil|black[\s_-]+seed[\s_-]+oil|nigella[\s_-]+sativa|black[\s_-]+cumin)\b/i,
    preferredGoals: ["immune","general_wellness"],
    hardBoundary: "Hard boundary: do not present Black Seed Oil as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "dim",
    canonicalFamily: "dim",
    displayName: "DIM",
    category: "other",
    productizationClass: "crosswalk_rescue",
    safetyBoundaryTier: "high",
    categoryHint: "single-active ingredient",
    patternKeywords: ["DIM","dim","diindolylmethane"],
    pattern: /\b(?:DIM|dim|diindolylmethane)\b/i,
    preferredGoals: ["womens_health","general_wellness"],
    hardBoundary: "Hard boundary: do not present DIM as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "hmb",
    canonicalFamily: "hmb",
    displayName: "HMB",
    category: "amino_acid",
    productizationClass: "crosswalk_rescue",
    safetyBoundaryTier: "high",
    categoryHint: "amino acid metabolite",
    patternKeywords: ["HMB","hmb","hydroxymethylbutyrate","beta-hydroxy beta-methylbutyrate"],
    pattern: /\b(?:HMB|hmb|hydroxymethylbutyrate|beta[\s_-]+hydroxy[\s_-]+beta[\s_-]+methylbutyrate)\b/i,
    preferredGoals: ["energy_performance","recovery","general_wellness"],
    hardBoundary: "Hard boundary: do not present HMB as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "mct_oil",
    canonicalFamily: "mct_oil",
    displayName: "MCT Oil",
    category: "lipid",
    productizationClass: "crosswalk_rescue",
    safetyBoundaryTier: "high",
    categoryHint: "oil ingredient",
    patternKeywords: ["MCT Oil","mct oil","medium-chain triglycerides"],
    pattern: /\b(?:MCT[\s_-]+Oil|mct[\s_-]+oil|medium[\s_-]+chain[\s_-]+triglycerides)\b/i,
    preferredGoals: ["heart_lipids","general_wellness"],
    hardBoundary: "Hard boundary: do not present MCT oil as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "nadh",
    canonicalFamily: "nadh",
    displayName: "NADH",
    category: "other",
    productizationClass: "crosswalk_rescue",
    safetyBoundaryTier: "high",
    categoryHint: "single-active ingredient",
    patternKeywords: ["NADH","nadh"],
    pattern: /\b(?:NADH|nadh)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Hard boundary: do not present NADH as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "phosphatidylserine",
    canonicalFamily: "phosphatidylserine",
    displayName: "Phosphatidylserine",
    category: "lipid",
    productizationClass: "crosswalk_rescue",
    safetyBoundaryTier: "high",
    categoryHint: "lipid ingredient",
    patternKeywords: ["Phosphatidylserine","phosphatidylserine"],
    pattern: /\b(?:Phosphatidylserine|phosphatidylserine)\b/i,
    preferredGoals: ["cognitive","general_wellness"],
    hardBoundary: "Hard boundary: do not present Phosphatidylserine as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "pqq",
    canonicalFamily: "pqq",
    displayName: "PQQ",
    category: "other",
    productizationClass: "crosswalk_rescue",
    safetyBoundaryTier: "high",
    categoryHint: "single-active ingredient",
    patternKeywords: ["PQQ","pqq"],
    pattern: /\b(?:PQQ|pqq)\b/i,
    preferredGoals: ["general_wellness"],
    hardBoundary: "Hard boundary: do not present PQQ as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "same",
    canonicalFamily: "same",
    displayName: "SAMe",
    category: "other",
    productizationClass: "crosswalk_rescue",
    safetyBoundaryTier: "high",
    categoryHint: "single-active ingredient",
    patternKeywords: ["SAMe","S-adenosyl methionine","SAM-e"],
    pattern: /\b(?:SAMe|S[\s_-]+adenosyl[\s_-]+methionine|SAM[\s_-]+e)\b/i,
    preferredGoals: ["sleep_stress","mood"],
    hardBoundary: "Hard boundary: do not present SAMe as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
  {
    sourceIngredientId: "tocotrienols",
    canonicalFamily: "tocotrienols",
    displayName: "Tocotrienols",
    category: "lipid",
    productizationClass: "crosswalk_rescue",
    safetyBoundaryTier: "high",
    categoryHint: "lipid ingredient",
    patternKeywords: ["Tocotrienols","tocotrienols","vitamin E tocotrienol"],
    pattern: /\b(?:Tocotrienols|tocotrienols|vitamin[\s_-]+E[\s_-]+tocotrienol)\b/i,
    preferredGoals: ["heart_lipids","general_wellness"],
    hardBoundary: "Hard boundary: do not present Tocotrienols as treating, preventing, or curing disease, replacing medication, or guaranteeing outcomes; keep comparison on disclosed identity, amount, form/source, and safety cautions.",
  },
] as const satisfies readonly NutriMinimalFullFamilyDefinition[];

export const NUTRI_MINIMAL_FULL_RUNTIME_FAMILIES = Array.from(
  new Set(NUTRI_MINIMAL_FULL_FAMILY_DEFINITIONS.map((row) => row.canonicalFamily)),
);

export type NutriMinimalRuntimeFamily =
  (typeof NUTRI_MINIMAL_FULL_FAMILY_DEFINITIONS)[number]["canonicalFamily"];

export const getNutriMinimalDefinitionForSourceIngredient = (
  sourceIngredientId: string | null | undefined,
): NutriMinimalFullFamilyDefinition | null => {
  const normalized = String(sourceIngredientId ?? "").trim().toLowerCase();
  return (
    NUTRI_MINIMAL_FULL_FAMILY_DEFINITIONS.find(
      (row) => row.sourceIngredientId === normalized,
    ) ?? null
  );
};

export const getNutriMinimalDefinitionForFamily = (
  family: string | null | undefined,
): NutriMinimalFullFamilyDefinition | null => {
  const normalized = String(family ?? "").trim().toLowerCase();
  return (
    NUTRI_MINIMAL_FULL_FAMILY_DEFINITIONS.find(
      (row) => row.canonicalFamily === normalized,
    ) ?? null
  );
};
