-- 20260102015000_barcode_scans_base_table.sql
-- Ensure barcode_scans exists before migrations that reference it.

begin;

create table if not exists public.barcode_scans (
  id bigint generated by default as identity primary key,
  barcode_gtin14 text not null,
  barcode_raw text,
  checksum_valid boolean,
  catalog_hit boolean not null default false,
  served_from text not null,
  dsld_label_id integer,
  snapshot_id text,
  brand_name text,
  product_name text,
  device_id text,
  request_id text,
  timing_total_ms integer,
  meta jsonb,
  created_at timestamptz not null default now(),
  constraint barcode_scans_gtin14_format_chk check (barcode_gtin14 ~ '^[0-9]{14}$')
);

alter table if exists public.barcode_scans enable row level security;
revoke all on table public.barcode_scans from anon, authenticated;
grant all on table public.barcode_scans to service_role;

commit;
