-- 20260226100000_barcode_contract_v2.sql
-- Barcode key contract hardening: reproducible schema, guarded write audit table, and v2 observability view.

begin;

-- ============================================================================
-- barcode_scans base table (for reproducible fresh environments)
-- ============================================================================

create table if not exists public.barcode_scans (
  id bigint generated by default as identity primary key,
  barcode_gtin14 text not null,
  barcode_raw text,
  checksum_valid boolean,
  catalog_hit boolean not null default false,
  served_from text not null,
  dsld_label_id integer,
  snapshot_id text,
  brand_name text,
  product_name text,
  device_id text,
  request_id text,
  timing_total_ms integer,
  meta jsonb,
  created_at timestamptz not null default now(),
  constraint barcode_scans_gtin14_format_chk check (barcode_gtin14 ~ '^[0-9]{14}$')
);

create index if not exists barcode_scans_barcode_created_idx
  on public.barcode_scans (barcode_gtin14, created_at desc);

create index if not exists barcode_scans_served_created_idx
  on public.barcode_scans (served_from, created_at desc);

create index if not exists barcode_scans_request_idx
  on public.barcode_scans (request_id);

alter table if exists public.barcode_scans enable row level security;
revoke all on table public.barcode_scans from anon, authenticated;
grant all on table public.barcode_scans to service_role;

drop policy if exists "service role full access" on public.barcode_scans;
create policy "service role full access"
on public.barcode_scans
for all
to service_role
using (true)
with check (true);

-- ============================================================================
-- Core cache key contract hardening
-- ============================================================================

alter table if exists public.barcode_regulatory_map
  add column if not exists barcode_raw text;

create index if not exists barcode_regulatory_map_barcode_raw_idx
  on public.barcode_regulatory_map (barcode_raw);

alter table if exists public.negative_cache
  add column if not exists barcode_raw text;

create index if not exists negative_cache_barcode_raw_idx
  on public.negative_cache (barcode_raw);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'barcode_regulatory_map_gtin14_format_chk'
      and conrelid = 'public.barcode_regulatory_map'::regclass
  ) then
    alter table public.barcode_regulatory_map
      add constraint barcode_regulatory_map_gtin14_format_chk
      check (barcode_gtin14 ~ '^[0-9]{14}$') not valid;
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'negative_cache_gtin14_format_chk'
      and conrelid = 'public.negative_cache'::regclass
  ) then
    alter table public.negative_cache
      add constraint negative_cache_gtin14_format_chk
      check (barcode_gtin14 ~ '^[0-9]{14}$') not valid;
  end if;
end;
$$;

-- ============================================================================
-- Guarded write bypass/audit table (blocked lower-rank writes)
-- ============================================================================

create table if not exists public.barcode_regulatory_map_candidates (
  id bigint generated by default as identity primary key,
  barcode_gtin14 text not null,
  barcode_raw text,
  incoming_npn text not null,
  incoming_source text not null,
  incoming_confidence double precision,
  incoming_expires_at timestamptz,
  incoming_rank integer,
  existing_npn text,
  existing_source text,
  existing_confidence double precision,
  existing_expires_at timestamptz,
  existing_rank integer,
  reason_code text not null,
  created_at timestamptz not null default now(),
  constraint barcode_regulatory_map_candidates_gtin14_format_chk check (barcode_gtin14 ~ '^[0-9]{14}$')
);

create index if not exists barcode_regulatory_map_candidates_barcode_created_idx
  on public.barcode_regulatory_map_candidates (barcode_gtin14, created_at desc);

create index if not exists barcode_regulatory_map_candidates_reason_idx
  on public.barcode_regulatory_map_candidates (reason_code, created_at desc);

alter table if exists public.barcode_regulatory_map_candidates enable row level security;
revoke all on table public.barcode_regulatory_map_candidates from anon, authenticated;
grant all on table public.barcode_regulatory_map_candidates to service_role;

drop policy if exists "service role full access" on public.barcode_regulatory_map_candidates;
create policy "service role full access"
on public.barcode_regulatory_map_candidates
for all
to service_role
using (true)
with check (true);

-- ============================================================================
-- Catalog RPC contract (resolved via DSLD canonical map)
-- ============================================================================

drop function if exists public.resolve_catalog_by_variants(p_variants text[]);

create or replace function public.resolve_catalog_by_variants(p_variants text[])
returns table (
  resolved_from text,
  barcode_gtin14 text,
  dsld_label_id integer,
  brand text,
  product_name text,
  category text,
  category_raw text,
  form text,
  serving_size_raw text,
  serving_size_count double precision,
  package_quantity double precision,
  package_unit text,
  servings_per_container double precision,
  active_ingredients_summary text,
  inactive_ingredients text,
  third_party_testing text,
  nsf_certified_for_sport boolean,
  informed_sport boolean,
  ifos_fish_oil boolean,
  cgmp_compliance text,
  dsld_pdf text,
  dsld_thumbnail text,
  image_url text
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  sql text;
begin
  if coalesce(array_length(p_variants, 1), 0) = 0 then
    return;
  end if;

  if to_regclass('public.dsld_barcode_canonical') is null
     or to_regclass('public.dsld_labels_meta') is null then
    return;
  end if;

  sql := $query$
    with input_variants as (
      select distinct on (lpad(regexp_replace(value, '\\D', '', 'g'), 14, '0'))
        lpad(regexp_replace(value, '\\D', '', 'g'), 14, '0') as barcode_gtin14,
        ord
      from unnest(coalesce($1, array[]::text[])) with ordinality as t(value, ord)
      where regexp_replace(value, '\\D', '', 'g') ~ '^[0-9]{8,14}$'
      order by lpad(regexp_replace(value, '\\D', '', 'g'), 14, '0'), ord
    ),
    matched as (
      select
        iv.barcode_gtin14,
        iv.ord,
        b.canonical_dsld_label_id as dsld_label_id,
        to_jsonb(m) as meta_json
      from input_variants iv
      join public.dsld_barcode_canonical b
        on b.barcode_normalized_gtin14 = iv.barcode_gtin14
      join public.dsld_labels_meta m
        on nullif(to_jsonb(m)->>'dsld_label_id', '')::integer = b.canonical_dsld_label_id
      order by iv.ord asc
      limit 1
    )
    select
      'dsld'::text as resolved_from,
      matched.barcode_gtin14,
      matched.dsld_label_id,
      nullif(matched.meta_json->>'brand', '') as brand,
      nullif(matched.meta_json->>'product_name', '') as product_name,
      nullif(matched.meta_json->>'category', '') as category,
      nullif(matched.meta_json->>'category_raw', '') as category_raw,
      nullif(matched.meta_json->>'form', '') as form,
      nullif(matched.meta_json->>'serving_size_raw', '') as serving_size_raw,
      nullif(matched.meta_json->>'serving_size_count', '')::double precision as serving_size_count,
      nullif(matched.meta_json->>'package_quantity', '')::double precision as package_quantity,
      nullif(matched.meta_json->>'package_unit', '') as package_unit,
      nullif(matched.meta_json->>'servings_per_container', '')::double precision as servings_per_container,
      nullif(matched.meta_json->>'active_ingredients_summary', '') as active_ingredients_summary,
      nullif(matched.meta_json->>'inactive_ingredients', '') as inactive_ingredients,
      nullif(matched.meta_json->>'third_party_testing', '') as third_party_testing,
      case lower(coalesce(matched.meta_json->>'nsf_certified_for_sport', ''))
        when 'true' then true
        when 't' then true
        when '1' then true
        when 'false' then false
        when 'f' then false
        when '0' then false
        else null
      end as nsf_certified_for_sport,
      case lower(coalesce(matched.meta_json->>'informed_sport', ''))
        when 'true' then true
        when 't' then true
        when '1' then true
        when 'false' then false
        when 'f' then false
        when '0' then false
        else null
      end as informed_sport,
      case lower(coalesce(matched.meta_json->>'ifos_fish_oil', ''))
        when 'true' then true
        when 't' then true
        when '1' then true
        when 'false' then false
        when 'f' then false
        when '0' then false
        else null
      end as ifos_fish_oil,
      nullif(matched.meta_json->>'cgmp_compliance', '') as cgmp_compliance,
      nullif(matched.meta_json->>'dsld_pdf', '') as dsld_pdf,
      nullif(matched.meta_json->>'dsld_thumbnail', '') as dsld_thumbnail,
      nullif(matched.meta_json->>'image_url', '') as image_url
    from matched;
  $query$;

  return query execute sql using p_variants;
end;
$$;

grant execute on function public.resolve_catalog_by_variants(text[]) to service_role;

-- ============================================================================
-- Observability view v2 (new served_from values)
-- ============================================================================

create or replace view public.non_dsld_barcodes_v2 as
with agg as (
  select
    barcode_gtin14,
    count(*) as scan_count,
    min(created_at) as first_seen_at,
    max(created_at) as last_seen_at
  from public.barcode_scans
  where catalog_hit = false
    and served_from in (
      'google_ai',
      'snapshot_cache',
      'wait_inflight',
      'resolution_engine_v2',
      'override_snapshot_cache'
    )
  group by barcode_gtin14
),
catalog_hits as (
  select distinct barcode_gtin14
  from public.barcode_scans
  where catalog_hit = true
)
select
  agg.barcode_gtin14,
  agg.scan_count,
  agg.first_seen_at,
  agg.last_seen_at,
  (s.payload_json -> 'product'::text) ->> 'brand'::text as guessed_brand,
  (s.payload_json -> 'product'::text) ->> 'name'::text as guessed_name,
  (s.payload_json -> 'product'::text) ->> 'category'::text as guessed_category,
  (s.payload_json -> 'product'::text) ->> 'form'::text as product_form,
  (s.payload_json -> 'product'::text) ->> 'imageUrl'::text as guessed_image_url,
  (s.payload_json ->> 'status'::text) as snapshot_status,
  s.id as snapshot_id,
  s.updated_at as snapshot_updated_at,
  s.created_at as snapshot_created_at
from agg
left join lateral (
  select snapshots.id, snapshots.created_at, snapshots.updated_at, snapshots.payload_json
  from public.snapshots
  where snapshots.source = 'barcode'::text
    and snapshots.key = agg.barcode_gtin14
  order by snapshots.updated_at desc, snapshots.created_at desc
  limit 1
) s on true
left join catalog_hits ch on ch.barcode_gtin14 = agg.barcode_gtin14
where ch.barcode_gtin14 is null
order by agg.scan_count desc;

-- ============================================================================
-- DB contract verification RPC (CI/maintainer gate)
-- ============================================================================

create or replace function public.verify_barcode_contract()
returns table (
  requirement text,
  ok boolean,
  details text
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  return query
  select
    'table:barcode_scans'::text,
    to_regclass('public.barcode_scans') is not null,
    'barcode scan log table exists'::text;

  return query
  select
    'table:barcode_regulatory_map'::text,
    to_regclass('public.barcode_regulatory_map') is not null,
    'regulatory map table exists'::text;

  return query
  select
    'table:negative_cache'::text,
    to_regclass('public.negative_cache') is not null,
    'negative cache table exists'::text;

  return query
  select
    'function:resolve_catalog_by_variants'::text,
    exists (
      select 1
      from pg_proc p
      join pg_namespace n on n.oid = p.pronamespace
      where n.nspname = 'public'
        and p.proname = 'resolve_catalog_by_variants'
    ),
    'catalog resolver RPC exists'::text;

  return query
  select
    'index:barcode_regulatory_map_barcode_raw_idx'::text,
    to_regclass('public.barcode_regulatory_map_barcode_raw_idx') is not null,
    'barcode_raw index exists on barcode_regulatory_map'::text;

  return query
  select
    'index:negative_cache_barcode_raw_idx'::text,
    to_regclass('public.negative_cache_barcode_raw_idx') is not null,
    'barcode_raw index exists on negative_cache'::text;

  return query
  select
    'view:non_dsld_barcodes_v2'::text,
    to_regclass('public.non_dsld_barcodes_v2') is not null,
    'v2 observability view exists'::text;
end;
$$;

grant execute on function public.verify_barcode_contract() to service_role;

commit;
