-- 20260106120000_lnhpd_raw_records.sql
-- Raw LNHPD API ingestion table for paged exports.

begin;

create table if not exists public.lnhpd_raw_records (
  id bigint generated by default as identity primary key,
  endpoint text not null,
  record_hash text not null,
  lnhpd_id bigint,
  payload jsonb not null,
  dataset_version text,
  fetched_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists lnhpd_raw_records_endpoint_hash_idx
  on public.lnhpd_raw_records (endpoint, record_hash);

create index if not exists lnhpd_raw_records_endpoint_lnhpd_idx
  on public.lnhpd_raw_records (endpoint, lnhpd_id);

commit;
