-- 20260105115000_dsld_reference_tables.sql
-- Build missing DSLD reference tables needed for fresh environments to avoid migration order failures.

begin;

create table if not exists public.dsld_labels_meta (
  dsld_label_id integer primary key,
  barcode_normalized_gtin14 text,
  canonical_dsld_label_id integer,
  dsld_product_version_code text,
  brand text,
  product_name text,
  serving_size_raw text,
  servings_per_container double precision,
  active_ingredients_summary text,
  inactive_ingredients text,
  dsld_pdf text,
  dsld_thumbnail text
);

create index if not exists dsld_labels_meta_barcode_idx
  on public.dsld_labels_meta (barcode_normalized_gtin14);

create table if not exists public.dsld_barcode_canonical (
  id bigint generated by default as identity primary key,
  barcode_normalized_gtin14 text not null,
  canonical_dsld_label_id integer not null
);

create unique index if not exists dsld_barcode_canonical_barcode_uq
  on public.dsld_barcode_canonical (barcode_normalized_gtin14);

create index if not exists dsld_barcode_canonical_label_idx
  on public.dsld_barcode_canonical (canonical_dsld_label_id);

create table if not exists public.dsld_facts (
  dsld_label_id integer primary key,
  facts_json jsonb not null,
  dataset_version text,
  extracted_at timestamptz not null default timezone('utc', now())
);

create index if not exists dsld_facts_dataset_version_idx
  on public.dsld_facts (dataset_version);

alter table if exists public.dsld_labels_meta enable row level security;
alter table if exists public.dsld_barcode_canonical enable row level security;
alter table if exists public.dsld_facts enable row level security;

revoke all on table public.dsld_labels_meta from anon, authenticated;
revoke all on table public.dsld_barcode_canonical from anon, authenticated;
revoke all on table public.dsld_facts from anon, authenticated;

grant all on table public.dsld_labels_meta to service_role;
grant all on table public.dsld_barcode_canonical to service_role;
grant all on table public.dsld_facts to service_role;

drop policy if exists "service role full access" on public.dsld_labels_meta;
drop policy if exists "service role full access" on public.dsld_barcode_canonical;
drop policy if exists "service role full access" on public.dsld_facts;

create policy "service role full access"
on public.dsld_labels_meta
for all
to service_role
using (true)
with check (true);

create policy "service role full access"
on public.dsld_barcode_canonical
for all
to service_role
using (true)
with check (true);

create policy "service role full access"
on public.dsld_facts
for all
to service_role
using (true)
with check (true);

commit;
